Repository codecov/codecov-bash, pull requests merged in 2019-12, with the labels that each got.

#239 Change cirrus-ci to match backend
  SHA1SUM
  codecov
  tests/test
Labels: bug, needs deployment

#233 Implementing parent picking
  SHA1SUM
  codecov
Labels: enhancement, needs deployment

#247 Bitbucket Pipelines: retrieve full SHA if shortened
  SHA1SUM
  codecov
  tests/test
Labels: bug, needs deployment

#244 Verify hash in CI
  .travis.yml
  SHA1SUM
Labels: enhancement

#245 Use shunit2 from Travis/Ubuntu xenial
  .gitignore
  .travis.yml
  shunit2-2.1.6.tgz
  tests/test
Labels: enhancement
