Repository codecov/codecov-bash, pull requests merged in 2020-03, with the labels that each got.

#268 fix(appveyor): support both linux and windows enviornments
  SHA1SUM
  codecov
  tests/test
Labels: bug, needs deployment

#270 Update CodeBuild CI detection to use CODEBUILD_CI env var
  SHA1SUM
  codecov
  env
  readme.md
  tests/env
  tests/test
Labels: enhancement, needs deployment

#147 fix: allow absolute paths for codecov.yml
  SHA1SUM
  codecov
Labels: bug, needs deployment

#276 fix: docs for development
  readme.md
Labels: enhancement

#274 Adjust coverage for .swift files too
  SHA1SUM
  codecov
Labels: enhancement, needs deployment

#279 Fix bitbucket repo slug for CodeBuild
  SHA1SUM
  codecov
  tests/test
Labels: bug, needs deployment

#164 fix gcovoutput option
  SHA1SUM
  codecov
Labels: bug, needs deployment
